services:
  fluxo-api:
    image: brsktdev/fluxo-api:main
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=${DB_CONNECTION_STRING}
      - Jwt__Secret=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    labels:
      caddy: api.fluxo.bonelesslab.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - caddy
      - internal
  
  fluxo-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - fluxo_db_data_prod:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  fluxo_db_data_prod:

networks:
  caddy:
    external: true
  internal:
    driver: bridge